package org.ippul.pi4j.examples.rules;

import org.ippul.pi4j.examples.model.UltrasonicRead;
import org.ippul.pi4j.examples.model.Blink;
import org.ippul.pi4j.examples.UltrasonicUtils;

rule "led blink"
    dialect "java"
    when
        $read : UltrasonicRead()
        $blink : Blink()
    then
        double $distance = UltrasonicUtils.calculateDistance($read);
        long $newBlinkValue = Double.valueOf(($distance * 1000)/2).longValue();
        if($newBlinkValue != $blink.getInterval()){
            $blink.setInterval($newBlinkValue);
            update($blink);
        }
        retract($read);
end